spring.application.name=conversion-business-service
server.port=8080

# spring.r2dbc.url=r2dbc:mysql://localhost:3309/db_springboot_backend


# BASE DE DATOS POSTGRESQL
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=admin

server.error.include-message=always


springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true