spring.application.name=conversion-exchange-rate
server.port=8082

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

springdoc.swagger-ui.urls[0].name=Orchestrator API
springdoc.swagger-ui.urls[0].url=/local-api.yaml

springdoc.swagger-ui.urls[1].name=External API
springdoc.swagger-ui.urls[1].url=/external-api.yaml


